allowLineBreaksInTitles: false
color: fuchsia
description: null
fieldLayouts:
  73a1e705-29a6-4961-b8a2-61969758e163:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-01T19:03:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5f1fa385-46f8-4945-9698-a72eab099aa7 # [O] Quotes Blocks
            handle: quotes
            instructions: null
            label: Quotes
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a5a0f72-1b94-4587-984d-a6e5dca9574c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-07T19:36:45+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Use "Headline" for the quote text.'
            type: craft\fieldlayoutelements\Tip
            uid: f3440f33-5385-4d80-9274-76d24f696013
            userCondition: null
          -
            dateAdded: '2026-05-07T19:36:45+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Use "Body" for the quote author'
            type: craft\fieldlayoutelements\Tip
            uid: 23afb921-b2fe-4126-9fc4-020d672b50e8
            userCondition: null
        name: Content
        uid: 65e800a3-3c83-4d51-8235-95f8a2a8ff5a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-07T21:51:44+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 11d08c34-6db8-410a-8820-1730d076b853 # [A] Theme Toggle
            handle: theme
            instructions: null
            label: Theme
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1be38c73-376a-4c43-b18a-c086fbeffe44
            userCondition: null
            warning: null
            width: 100
        name: Options
        uid: acf3cda3-f33f-4645-af9b-d6c0adc783ff
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-01T19:03:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8067a6b9-db4e-4674-a375-7bf78a108d31 # [M] Layout
            handle: layout
            instructions: null
            label: Layout
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c108f9b-12ac-4f61-b889-08d9e152ba08
            userCondition: null
            warning: null
            width: 100
        name: Layout
        uid: fbcfc551-a7ab-4162-93e7-9f432a837ae1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-01T19:03:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 622cbecd-d13d-4eba-8fc4-cbb1eb3d5f01 # [A] Plain Text
            handle: jumpToNavLabel
            instructions: null
            label: 'Jump To Nav Label'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 148405d0-92c6-4fd9-b487-20fdb93bacd4
            userCondition: null
            warning: null
            width: 100
        name: 'Jump To Nav'
        uid: 67f0ce07-c37a-4ade-9282-47726d026681
        userCondition: null
    thumbFieldKey: null
handle: quotes
hasTitleField: false
icon: message-quote
name: Quotes
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
