allowLineBreaksInTitles: false
color: amber
description: null
fieldLayouts:
  9520f370-64da-4338-8577-5f250a2364b5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-03T13:46:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a4169822-6f55-440b-9d65-40c8e938af74 # [O] Split Blocks
            handle: blocks
            instructions: null
            label: Blocks
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d601f04-c356-4918-bcfc-b1806ac2ee6f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b31da445-1a13-433d-899a-43ae1485c941
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-19T14:36:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 11d08c34-6db8-410a-8820-1730d076b853 # [A] Theme Toggle
            handle: theme
            instructions: null
            label: Theme
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e85c95e-5830-46b6-b0e0-9f421f3bc4b3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-08T08:27:59+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ccb32ef0-7553-4611-b276-0cc20062594f # [A] Toggle (Off)
            handle: imageIsContained
            instructions: "Use image's native aspect ratio (instead of default 7:5)"
            label: 'Contain Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52d756a3-4fbc-42ec-b659-9f6cc3e38ac9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T10:06:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b368570f-83f3-414b-9542-c0d7ff556ff1 # [A] Image (Badge)
            handle: badge
            instructions: null
            label: Badge
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd8b9677-d7ea-4a91-95d7-03c7840d4fc9
            userCondition: null
            warning: null
            width: 100
        name: Options
        uid: e25288e3-2c04-4368-8571-574685d517fd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-16T05:12:42+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 622cbecd-d13d-4eba-8fc4-cbb1eb3d5f01 # [A] Plain Text
            handle: jumpToNavLabel
            instructions: "The text that will appear in the 'Jump To' navigation for this section"
            label: 'Jump To Nav Label'
            required: false
            tip: 'Leave blank to exclude this section from the page navigation'
            type: craft\fieldlayoutelements\CustomField
            uid: 043b6a0a-40ee-44b6-a57f-a56618360fb0
            userCondition: null
            warning: null
            width: 100
        name: 'Jump To Nav'
        uid: 8be16a83-8987-4a7f-8840-488065a401ac
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-18T15:24:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8067a6b9-db4e-4674-a375-7bf78a108d31 # [M] Layout
            handle: layout
            instructions: null
            label: Layout
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f404e4d3-8277-48f7-8f27-41cc69c0b443
            userCondition: null
            warning: null
            width: 100
        name: Layout
        uid: 716ecbe0-a69c-49b0-bea8-80f51ce6a005
        userCondition: null
    thumbFieldKey: null
handle: split
hasTitleField: false
icon: diamond-half-stroke
name: Split
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
