allowLineBreaksInTitles: false
color: yellow
description: null
fieldLayouts:
  22b908ff-a9e0-4d94-a8e1-43f6a8782372:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-05T13:39:05+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a0c3ed96-a2a3-43ee-9549-34a9b974e520 # [A] Image (Spotlight)
            handle: image
            instructions: null
            label: Image
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdfa0b3c-3048-4bf7-83e7-33c382358561
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3f92f2b0-b91b-439a-b210-40b358e8d203
        userCondition: null
    thumbFieldKey: null
handle: spotlightBackground
hasTitleField: false
icon: adversal
name: 'Spotlight: Background'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
