allowLineBreaksInTitles: false
color: pink
description: null
fieldLayouts:
  360cdf1e-e45f-427c-b5e0-531acb3b7621:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-29T17:02:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2e64758c-85db-43e2-bc3e-b7de81ff8ffd
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2026-01-29T17:02:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ba11f21a-24e9-4a1e-b26f-7f7e0096204f # [A] Rich Text (Inline Basic)
            handle: body
            instructions: null
            label: Body
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4f021bf-8dbe-4032-ac1b-1410c39469ec
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: c33b8d99-75d1-47cf-93bd-0be2a3cdd342
        userCondition: null
    thumbFieldKey: null
handle: tableInfoRow
hasTitleField: true
icon: table-rows
name: 'Table Info: Row'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
