defaultPlacement: end
fieldLayouts:
  0123ae01-1a6a-4233-a06a-138f02a2d54f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-15T11:39:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 5a3c33c8-617d-4c6b-805c-5c0376f7425f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T11:39:01+00:00'
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 5479c09b-a5b5-45b0-8078-1bdae939fe58
            userCondition: null
            warning: null
          -
            attribute: newWindow
            dateAdded: '2026-04-15T11:39:01+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 290e80f7-bf26-4a88-834e-b6eb2a70f5ea
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 6819afd5-7c8b-43eb-9cff-f461ddef0c61
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2026-04-15T11:39:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: b42ad3fd-5f0c-404f-bd84-1feaea8def80
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2026-04-15T11:39:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 92958a0a-46ee-437e-a99c-096d537a0e3f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            dateAdded: '2026-04-15T11:39:01+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: ca9a795d-7054-426b-ba05-4097f1e5b3bf
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: ba823ea0-5e41-4d6b-b005-99fe73dd80c0
        userCondition: null
    thumbFieldKey: null
handle: secondaryMobile
instructions: null
maxNodes: null
name: 'Secondary (Mobile)'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: '1'
propagationMethod: all
showSiteMenu: true
siteSettings:
  5aa67919-8786-42f8-bdac-59fc2021ab07: # Keel
    enabled: false
  177bf172-3ebf-45b8-b634-b17fda7ddef5: # Secondary
    enabled: true
  3067f776-da80-45b3-8266-dda80e9a9fcc: # Primary
    enabled: true
  f4bfd477-f2a5-437c-9c51-80d72728993e: # Tertiary
    enabled: true
sortOrder: 6
structure:
  maxLevels: 1
  uid: c86f69d0-b5bc-441b-b7ff-d6c8ee2fbd70
