columnSuffix: null
handle: aImageFeatured
instructions: null
name: '[A] Image (Featured)'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:e36ed945-fdea-437f-870e-f52a749f7b50' # Featured
  defaultUploadLocationSubpath: '{ object.site.handle }/blog-thumbnail'
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: thumbs
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:e36ed945-fdea-437f-870e-f52a749f7b50' # Featured
  restrictedLocationSubpath: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: thumbs
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
