columnSuffix: null
handle: aImageHero
instructions: null
name: '[A] Image (Hero)'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:005d0d61-367b-48d5-abd7-e23ee15a7487' # Icons
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: thumbs
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:c28fd67d-a4ad-43b9-bddb-5a0d8950e96d' # Hero
  restrictedLocationSubpath: '{ object.site.handle }/hero'
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: thumbs
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
