columnSuffix: null
handle: aOrientation
instructions: null
name: '[A] Orientation'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Default
        -
          - value
          - ''
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Portrait
        -
          - value
          - portrait
        -
          - icon
          - image-portrait
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Landscape
        -
          - value
          - landscape
        -
          - icon
          - image
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Square
        -
          - value
          - square
        -
          - icon
          - stop
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\RadioButtons
