columnSuffix: null
handle: aRichTextInlineBasic
instructions: null
name: '[A] Rich Text (Inline Basic)'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  fullGraphqlData: true
  headingLevels: false
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: null
  jsFile: null
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - bold
    - italic
    - '|'
    - link
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
