columnSuffix: null
handle: blogBuilder
instructions: null
name: 'Builder: Blog'
searchable: false
settings:
  createButtonLabel: 'New Block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 9a49234d-00a9-469f-9f8d-f017e2461ab6 # Text
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 3b45a144-d998-4ea9-9de7-61f10ba61933 # Image
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - cd6acee0-04df-4809-bcb1-6a4d0f985569 # Video
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
