columnSuffix: null
handle: ioCarousel
instructions: null
name: '[IO] Carousel'
searchable: false
settings:
  displayDominantColorPalette: true
  displayLazyLoadPlaceholderImages: true
  displayOptimizedImageVariants: true
  fieldVolumeSettings:
    __assoc__:
      -
        - carousel
        - '*'
  ignoreFilesOfType:
    - image/svg
    - image/gif
    - application/pdf
  variants:
    -
      __assoc__:
        -
          - width
          - '205'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '247'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '333'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '60'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '418'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '60'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '504'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
