columnSuffix: null
handle: ioGridCardPortrait
instructions: null
name: '[IO] Grid Card (Portrait)'
searchable: false
settings:
  displayDominantColorPalette: true
  displayLazyLoadPlaceholderImages: true
  displayOptimizedImageVariants: true
  fieldVolumeSettings:
    __assoc__:
      -
        - gridCard
        - '*'
  ignoreFilesOfType:
    - image/svg
    - image/gif
    - application/pdf
  variants:
    -
      __assoc__:
        -
          - width
          - '298'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '5'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '60'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '262'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '5'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '384'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '5'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '469'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '5'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - ''
translationKeyFormat: null
translationMethod: site
type: nystudio107\imageoptimize\fields\OptimizedImages
