defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 05ffaad9-22a2-4b48-99eb-4f1ee62af176 # General: Category
handle: category
maxAuthors: 1
minAuthors: 1
name: Category
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: none
siteSettings:
  177bf172-3ebf-45b8-b634-b17fda7ddef5: # Secondary
    enabledByDefault: true
    hasUrls: true
    template: category/_entry.twig
    uriFormat: 'category/{slug}'
  3067f776-da80-45b3-8266-dda80e9a9fcc: # Primary
    enabledByDefault: true
    hasUrls: true
    template: category/_entry.twig
    uriFormat: 'category/{slug}'
  f4bfd477-f2a5-437c-9c51-80d72728993e: # Tertiary
    enabledByDefault: true
    hasUrls: true
    template: category/_entry.twig
    uriFormat: 'category/{slug}'
type: channel
